### ISSUE TITLE
Add aria2c to PATH

### ISSUE THREAD

**Issue by Master-Hash** [M2Team/NanaGet#5]
既然 NanaGet 有自带的 aria2c，希望像 NanaZip 将 7z 加入 PATH 一样，将 aria2c 加入 PATH。

**Comment by MouriNaruto** [comment]
由于 NanaGet 未来有考虑自研下载引擎的可能性，而自研下载引擎并不想完整继承 aria2 的全部行为，遂 NanaGet 不会将 aria2c 加入 PATH。（事实上 NanaGet 的 aria2 实例的 RPC 端口也是随机的，为了避免和其他 aria2 实例冲突。）

毛利
